version: '3'
services:
    lst_node:
        container_name: lst_node
        image: node:10.15.0
        volumes:
            - ./:/app
        working_dir: /app
        depends_on:
            - lst_mongo
            - lst_redis
        ports:
            - 5000:5000
        command: yarn server:dev
    lst_mongo:
        container_name: lst_mongo
        image: mongo:4.0.5
        expose:
            - 27017
        ports:
            - '27020:27017'
    lst_redis:
        container_name: lst_redis
        image: redis
        ports:
            - '6380:6379'